
name: bash4armCC

on:
  # Run every Monday at 00:07 (to be a little off the peak time)
  # schedule:
  #   - cron: '7 0 * * 1'

  # Manual running enabled
  workflow_dispatch:

# Allow workflow to write to repository
permissions:
  contents: write

jobs:
  Cross-Compile:

    runs-on: ubuntu-latest
  
    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y gcc-aarch64-linux-gnu curl

      - name: Fetch latest bash version
        run: |
          version=$(curl -s https://ftp.gnu.org/gnu/bash/ | grep -o "bash-[0-9]\+\(\.[0-9]\+\)\{0,2\}\.tar\.gz" | grep -o '[0-9]\+\(\.[0-9]\+\)\{0,2\}' | sort -V | tail -1)
          echo "Latest bash version: $version"
          echo "BASH_VERSION=$version" >> $GITHUB_ENV

      - name: Download source code
        run: |
          curl -sO "https://ftp.gnu.org/gnu/gnu-keyring.gpg"
          curl -sO "https://ftp.gnu.org/gnu/bash/bash-${{ env.BASH_VERSION }}.tar.gz"
          curl -sO "https://ftp.gnu.org/gnu/bash/bash-${{ env.BASH_VERSION }}.tar.gz.sig"
          gpg --verify --keyring gnu-keyring.gpg "bash-${{ env.BASH_VERSION }}.tar.gz.sig" "bash-${{ env.BASH_VERSION }}.tar.gz"
          tar -xzvf "bash-${{ env.BASH_VERSION }}.tar.gz"

      - name: Build and compile for aarch64
        run: |
          cd "bash-${{ env.BASH_VERSION }}"
          export CC=aarch64-linux-gnu-gcc
          ./configure --host=aarch64-linux-gnu CFLAGS="-static" LDFLAGS="-static"
          make
      
      - name: Create release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: bash-${{ env.BASH_VERSION }}/bash
          overwrite: true
          tag: v${{ env.BASH_VERSION }}
